channels:
- conda-forge
- defaults
dependencies:
# Definites
- imbalanced-learn
- ipython
- joblib
- matplotlib
- pandas
- numpy
- pip
- python=3.10
- scikit-optimize
- scikit-learn
- sqlite
- xgboost
- pyodbc
- scipy
- cloudpickle
- pyarrow
- sqlalchemy
- ipykernel
- mlflow
- jupyterlab

# Dependencies
- ruamel.yaml=0.17.32
- setuptools=80.8.0
- msrest
- pydash
- colorama
- requests
- six
- typing-extensions
- cryptography
- isodate
- adal
- argcomplete
- backports.tempfile
- contextlib2
- humanfriendly
- jmespath
- jsonpickle
- knack<0.13.0
- ndg-httpsclient
- packaging
- paramiko<4.0.0
- pathspec
- pkginfo
- PyJWT
- pyopenssl
- python-dateutil
- pytz
- SecretStorage
- urllib3
- jsonschema
- pyyaml
- fsspec
- strictyaml
- tqdm
- marshmallow=3.23.2
- _libgcc_mutex
- _openmp_mutex
- _py-xgboost-mutex
- annotated-types
- anyio
- asttokens
- blas
- bottleneck
- brotli
- brotli-bin
- brotli-python
- bzip2
- ca-certificates
- certifi
- comm
- cycler
- debugpy
- decorator
- distro
- exceptiongroup
- executing
- freetype
- h11
- httpcore
- httpx
- idna
- importlib-metadata
- jedi
- jiter
- jpeg
- jupyter_client
- jupyter_core
- kiwisolver
- krb5
- lcms2
- ld_impl_linux-64
- lerc
- libbrotlicommon
- libbrotlidec
- libbrotlienc
- libdeflate
- libedit
- libffi
- libgcc
- libgcc-ng
- libgfortran
- libgfortran-ng
- libgfortran5
- libgomp
- libopenblas
- libpng
- libsodium
- libstdcxx
- libstdcxx-ng
- libtiff
- libuuid
- libwebp-base
- libxgboost
- lz4-c
- matplotlib-inline
- munkres
- ncurses
- nest-asyncio
- numexpr
- numpy-base
- openai
- openblas
- openjpeg
- openssl
- opentelemetry-api
- opentelemetry-sdk
- opentelemetry-semantic-conventions
- parso
- pexpect
- pickleshare
- platformdirs
- prompt-toolkit
- psutil
- ptyprocess
- pure_eval
- py-xgboost
- pyaml
- pydantic
- pydantic-core
- pygments
- python-dateutil
- python-tzdata
- python_abi
- pyzmq
- readline
- seaborn
- six
- sklearn-compat
- sniffio
- stack_data
- threadpoolctl
- tk
- tornado
- traitlets
- typing-extensions
- typing_extensions
- unicodedata2
- unixodbc
- wcwidth
- wheel
- xz
- yaml
- zeromq
- zipp
- zlib
- zstd
- notebook
